BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-licheepi4a"
BBFILE_PATTERN_meta-licheepi4a = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-licheepi4a = "10"

LAYERDEPENDS_meta-licheepi4a = "core openembedded-layer"
LAYERSERIES_COMPAT_meta-licheepi4a = "kirkstone scarthgap"
