no-resolv
server=8.8.8.8
server=2001:4860:4860::8888
bind-interfaces

dhcp-range=10.0.2.10,10.0.2.200,255.255.255.0,12h
dhcp-option=option:router,10.0.2.3
dhcp-option=option:dns-server,10.0.2.3

address=/controller.local/10.0.2.3

enable-ra
dhcp-range=fd00:a::10,fd00:a::ff,ra-names,64,12h
